server:
  port: 9080
spring:
  application:
    name: admin-server
#  boot:
#    admin:
#      client:
#        url: http://localhost:9080
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    health-check-url-path: /actuator/health
    #metadata-map:
    #  instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

management:
  endpoint:
    health:
      show-details: ALWAYS

endpoints:
  web:
    exposure:
      include: "*"