server:
  port: 8993

keycloak:
  server-uri: ${KEYCLOAK_SERVER_URI:http://localhost:8091}
  base-uri: ${KEYCLOAK_SERVER:http://localhost:8091/auth/realms/}
  #jwk-set-uri: http://keycloak_server:8771/auth/realms/payment-chain/protocol/openid-connect/certs
  jwk-set-uri: ${keycloak.base-uri}PaymentChain/protocol/openid-connect/certs
  certs-id: ${KEYCLOAK_REAL_ID:t2Isk7PqpwFMjJrMqs8RhNofNRjHynkAN0RNqLHQG6I}
  token-uri: ${keycloak.base-uri}PaymentChain/protocol/openid-connect/token
  user-info-uri: ${keycloak.base-uri}PaymentChain/protocol/openid-connect/userinfo
  authorization:
    uri: ${keycloak.base-uri}PaymentChain/protocol/openid-connect/auth
    grant-type: password
    grant-type-refresh: refresh_token
  logout: ${keycloak.base-uri}PaymentChain/protocol/openid-connect/logout
  client:
    id: front-angular-billing-app
    secret: qwerty
  scope: profile
logging:
  level:
    root: INFO